inherit_from: .rubocop_todo.yml
require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2

Gemspec/DeprecatedAttributeAssignment: # new in 1.30
  Enabled: true

Gemspec/RequireMFA: # new in 1.23
  Enabled: true

Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true

Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true

Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true

Layout/SpaceBeforeBrackets: # new in 1.7
  Enabled: true

Lint/AmbiguousAssignment: # new in 1.7
  Enabled: true

Lint/AmbiguousOperatorPrecedence: # new in 1.21
  Enabled: true

Lint/AmbiguousRange: # new in 1.19
  Enabled: true

Lint/ConstantOverwrittenInRescue: # new in 1.31
  Enabled: true

Lint/DeprecatedConstants: # new in 1.8
  Enabled: true
